version: '3'
services:
  backend-dev-db:
    image: mysql:8.0
    hostname: localhost
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: agentur
      MYSQL_PASSWORD: password
      # MYSQL_USER: root
    networks:
      - coderzhunt
networks:
  coderzhunt:
